"""
State schema for the SFSA Agentic RAG workflow.

This module defines the shared state that flows through all nodes in the
LangGraph workflow. Each node receives the current state and returns a
dictionary of updates that are merged into the state.

The state progressively accumulates information as it moves through:
1. Retrieval → Context from vector DB
2. Agent 1 → Context sufficiency decision
3. Agent 2 → Web search (conditional)
4. Context Combination → Merged context
5. Generation → LLM response
6. Agent 3 → Validation and refinement
7. Final Output → Formatted response

Based on the KnowMat2 state pattern.
"""

from typing import TypedDict, List, Tuple, Optional, Dict, Any
from langchain_core.documents import Document


class SFSAAgenticState(TypedDict, total=False):
    """
    Shared state passed between LangGraph nodes in the agentic RAG workflow.
    
    All fields are optional (total=False) and are populated progressively
    as the workflow advances through different nodes.
    
    Workflow Progression
    --------------------
    START
      ↓
    retrieve_context: Sets retrieved_docs, retrieved_sources
      ↓
    check_context_sufficiency: Sets context_sufficient, sufficiency_reasoning
      ↓
    [CONDITIONAL: If context insufficient]
    web_search: Sets needs_web_search, reformulated_query, web_search_results, web_sources
      ↓
    combine_context: Sets final_context, all_sources
      ↓
    generate_response: Sets current_query, llm_response, updates response_history
      ↓
    validate_response: Sets response_satisfactory, refined_question, validation_count, validation_history
      ↓
    [CONDITIONAL: If not satisfactory and count < max_attempts, loop back to generate_response]
      ↓
    format_final_output: Sets final_response, final_sources
      ↓
    END
    
    Attributes
    ----------
    
    Input Fields (Set at START)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    user_query : str
        The original question from the user. This never changes and is used
        for validation checks throughout the workflow.
    
    conversation_history : List[Tuple[str, str]]
        Optional conversation history for multi-turn interactions.
        Each tuple is (user_message, assistant_message).
    
    max_validation_attempts : int
        Maximum number of validation loop iterations (default: 2).
        Set from settings at workflow initialization.
    
    
    Vector DB Retrieval (retrieve_context node)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    retrieved_docs : List[Document]
        Documents retrieved from the FAISS vector database.
        Each Document has page_content and metadata (including source).
    
    retrieved_sources : List[str]
        List of source paths/URLs from retrieved documents.
        Used for citation and source tracking.
    
    
    Agent 1: Context Sufficiency Check (check_context_sufficiency node)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    context_sufficient : bool
        True if retrieved documents are sufficient to answer the query,
        False if web search is needed.
    
    sufficiency_reasoning : Optional[str]
        Brief explanation of why context was deemed sufficient/insufficient.
        Useful for debugging and understanding Agent 1's decision.
    
    
    Agent 2: Web Search (web_search node, conditional)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    needs_web_search : bool
        Set to True when context_sufficient is False, triggers web search.
    
    reformulated_query : Optional[str]
        The original query reformulated for optimal web search results.
        Generated by Agent 2 using LLM.
    
    web_search_results : Optional[str]
        Formatted text content from web search results (Tavily + URLLoader).
        Contains full page content from top search results.
    
    web_sources : Optional[List[str]]
        List of URLs from web search results for citation.
    
    
    Combined Context (combine_context node)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    final_context : str
        Merged context from vector DB and web search (if performed).
        This is what gets passed to the LLM for generation.
    
    all_sources : List[str]
        Combined list of all sources (vector DB + web) for final citation.
    
    
    Generation (generate_response node)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    current_query : str
        The query to answer in the current generation attempt.
        Initially equals user_query, but may become refined_question
        in subsequent validation loop iterations.
    
    llm_response : str
        The most recent response generated by the LLM.
    
    response_history : List[Dict[str, Any]]
        History of all generation attempts, each containing:
        - query: The query that was answered
        - response: The LLM's response
        - attempt: Attempt number (1-indexed)
        - is_original: True if answering the original user_query
    
    
    Agent 3: Response Validation (validate_response node)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    response_satisfactory : bool
        True if the LLM response fully addresses the user's original query,
        False if refinement is needed.
    
    refined_question : Optional[str]
        A refined version of the original query that explicitly includes
        what was missing from the previous response. Generated by Agent 3.
        Becomes the new current_query for the next generation attempt.
    
    validation_count : int
        Number of validation attempts performed (0-indexed).
        Compared against max_validation_attempts to limit loops.
    
    validation_history : List[Dict[str, Any]]
        History of all validation attempts, each containing:
        - attempt: Attempt number (1-indexed)
        - response: The response that was validated
        - verdict: "yes" or "no"
        - refined_question: The refined question (if verdict was "no")
    
    
    Final Output (format_final_output node)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    final_response : str
        The final formatted response to return to the user.
        - If satisfactory: Uses last llm_response
        - If max attempts reached: Combines all responses from response_history
    
    final_sources : List[str]
        Formatted list of all sources used in generating the response.
        Includes both vector DB sources and web sources.
    """
    
    # ═══════════════════════════════════════════════════════════════════════
    # Input Fields
    # ═══════════════════════════════════════════════════════════════════════
    user_query: str
    conversation_history: List[Tuple[str, str]]
    max_validation_attempts: int
    
    # ═══════════════════════════════════════════════════════════════════════
    # Query Contextualization (contextualize_query node)
    # ═══════════════════════════════════════════════════════════════════════
    contextualized_query: str  # Query rewritten with conversation context
    contextualization_reasoning: Optional[str]  # Why the query was rewritten
    
    # ═══════════════════════════════════════════════════════════════════════
    # Vector DB Retrieval (retrieve_context node)
    # ═══════════════════════════════════════════════════════════════════════
    retrieved_docs: List[Document]
    retrieved_formatted: str  # Formatted string for LLM
    sources: List[Dict[str, Any]]  # Source metadata from retrieval
    
    # ═══════════════════════════════════════════════════════════════════════
    # Agent 1: Context Sufficiency (check_context_sufficiency node)
    # ═══════════════════════════════════════════════════════════════════════
    context_sufficient: bool
    context_sufficiency_reasoning: Optional[str]
    
    # ═══════════════════════════════════════════════════════════════════════
    # Agent 2: Web Search (web_search node, conditional)
    # ═══════════════════════════════════════════════════════════════════════
    web_search_query: Optional[str]  # Reformulated query for web search
    web_search_results: List[Dict[str, Any]]  # Raw Tavily results
    web_search_formatted: Optional[str]  # Formatted for LLM
    
    # ═══════════════════════════════════════════════════════════════════════
    # Combined Context (combine_context node)
    # ═══════════════════════════════════════════════════════════════════════
    combined_context: str  # M erged context from vector DB + web
    
    # ═══════════════════════════════════════════════════════════════════════
    # Generation (generate_response node)
    # ═══════════════════════════════════════════════════════════════════════
    current_response: str  # Latest generated response
    accumulated_responses: List[str]  # All responses from attempts
    validation_attempts: int  # Current attempt counter
    
    # ═══════════════════════════════════════════════════════════════════════
    # Agent 3: Response Validation (validate_response node)
    # ═══════════════════════════════════════════════════════════════════════
    response_satisfactory: bool
    validation_reasoning: Optional[str]
    refined_query: Optional[str]  # Refined query for re-generation
    validation_history: List[Dict[str, Any]]  # History of all validation attempts
    
    # ═══════════════════════════════════════════════════════════════════════
    # Final Output (format_final_output node)
    # ═══════════════════════════════════════════════════════════════════════
    final_response: str
    final_output: Dict[str, Any]  # Complete final output dict
    
    # ═══════════════════════════════════════════════════════════════════════
    # Error Tracking
    # ═══════════════════════════════════════════════════════════════════════
    error: Optional[str]  # Any error messages from nodes


# ─── Helper Functions for State Manipulation ────────────────────────────────

def initialize_state(
    user_query: str,
    conversation_history: Optional[List[Tuple[str, str]]] = None,
    max_validation_attempts: int = 2
) -> SFSAAgenticState:
    """
    Initialize a new state dictionary for the workflow.
    
    Parameters
    ----------
    user_query : str
        The user's question to answer
    conversation_history : Optional[List[Tuple[str, str]]]
        Previous conversation turns, if any
    max_validation_attempts : int
        Maximum validation loop iterations (default: 2)
    
    Returns
    -------
    SFSAAgenticState
        Initialized state with input fields set
    """
    return SFSAAgenticState(
        user_query=user_query,
        conversation_history=conversation_history or [],
        max_validation_attempts=max_validation_attempts,
        validation_attempts=0,
        accumulated_responses=[],
        validation_history=[],
    )


def format_sources_for_display(sources: List) -> str:
    """
    Format a list of sources for user-friendly display.
    
    Parameters
    ----------
    sources : List
        List of source paths/URLs (as strings) or source dicts with metadata
    
    Returns
    -------
    str
        Formatted string with numbered sources
    """
    if not sources:
        return "No sources available."
    
    # Convert sources to strings if they're dicts
    source_strings = []
    for src in sources:
        if isinstance(src, dict):
            # Extract appropriate string based on source type
            if src.get("source_type") == "web_search":
                # Web source - use URL
                source_str = src.get("url", "Unknown web source")
            else:
                # Vector DB source - use source field
                source_str = src.get("source", "Unknown source")
                # Add page info if available
                if "page" in src:
                    source_str += f", page {src['page']}"
                elif "page_number" in src:
                    source_str += f", page {src['page_number']}"
            source_strings.append(source_str)
        else:
            # Already a string
            source_strings.append(str(src))
    
    # Remove duplicates while preserving order
    seen = set()
    unique_sources = []
    for src in source_strings:
        if src not in seen:
            seen.add(src)
            unique_sources.append(src)
    
    formatted = "**Sources:**\n"
    for i, source in enumerate(unique_sources, 1):
        # Shorten long paths/URLs for readability
        display = source
        if len(display) > 80:
            display = display[:77] + "..."
        formatted += f"{i}. {display}\n"
    
    return formatted


def get_state_summary(state: SFSAAgenticState) -> str:
    """
    Generate a human-readable summary of the current state.
    Useful for debugging and logging.
    
    Parameters
    ----------
    state : SFSAAgenticState
        Current workflow state
    
    Returns
    -------
    str
        Summary of key state fields
    """
    lines = [
        "═══ State Summary ═══",
        f"User Query: {state.get('user_query', 'N/A')}",
        f"Current Query: {state.get('current_query', 'N/A')}",
        f"Context Sufficient: {state.get('context_sufficient', 'N/A')}",
        f"Web Search Performed: {state.get('needs_web_search', False)}",
        f"Validation Count: {state.get('validation_count', 0)}/{state.get('max_validation_attempts', 2)}",
        f"Response Satisfactory: {state.get('response_satisfactory', 'N/A')}",
    ]
    
    if state.get('response_history'):
        lines.append(f"Response Attempts: {len(state['response_history'])}")
    
    if state.get('all_sources'):
        lines.append(f"Total Sources: {len(state['all_sources'])}")
    
    lines.append("═══════════════════")
    
    return "\n".join(lines)
